spring:
  jackson:
    time-zone: America/Sao_Paulo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/client
    username: root
server:
  port: 8080

  ## cmowemvof43momefvowm4