spring:
  jackson:
    time-zone: America/Sao_Paulo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3030/client
    username: root
    password: root

server:
  port: 8080

# caralho